apiVersion: apps/v1
kind: Deployment
metadata:
  name: hd-api
  labels:
    app: hd-api
spec:
  selector:
    matchLabels:
      app: hd-api
  template:
    metadata:
      labels:
        app: hd-api
    spec:
      containers:
        - name: hd-api
          image: hd-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          envFrom:
            - configMapRef:
                name: hd-config
          volumeMounts:
            - name: hd-secret-volume
              mountPath: /etc/secret-volume
              readOnly: true
            - name: hd-image-local-path
              mountPath: /code/images
              readOnly: false
      volumes:
        - name: hd-secret-volume
          secret:
            secretName: hd-secret
        - name: hd-image-local-path
          hostPath:
            path: /data/hd-images
            type: DirectoryOrCreate
